[package]
name = "buzzkey"
version = "0.1.0"
authors = ["Floozutter <me@floozutter.site>"]
edition = "2018"

[dependencies]
midir = "0.7"
buttplug = "4.0"
tokio = { version = "1.7", features = ["full"] }
futures = "0.3.15"
futures-timer = "3.0"
